# k-均值聚类算法

In [5]:
from numpy import *

def loadDataSet(fileName):
    '''导入文件'''
    dataMat = []
    with open(fileName) as fr:
        for line in fr.readlines():
            curLine = line.strip().split('\t')
            fltLine = map(float, curLine)
            dataMat.append(fltLine)
    return dataMat

def distEclud(vecA, vecB):
    '''欧几里得距离'''
    return sqrt(sum(power(vecA - vecB, 2)))

def randCent(dataSet, k):
    '''随机生成范围内的均值向量'''
    n = shape(dataSet)[1]
    centroids = mat(zeros((k, n)))
    for j in xrange(n):
        minJ = min(dataSet[:, j])
        rangeJ = float(max(dataSet[:, j]) - minJ)
        centroids[:, j] = minJ + rangeJ*random.rand(k, 1)
    return centroids

In [8]:
datMat = mat(loadDataSet('./data/testSet.txt'))

**输入**：样本集 $D=\{x_1,x_2,\dots,x_n\}$; 聚类簇数 $k$ .  
**过程**：  
从 $D$ 中随机选择 $k$ 个样本作为初始均值向量 $\{\mu_1,\mu_2,\dots,\mu_n\}$  
**repeat**  
&emsp; 令 $C_i = \emptyset (1\le i\le k)$  
&emsp; **for** $j = 1, 2, \dots, m$ **do**  
&emsp;&emsp; 计算样本 $\mathbf{x_j}$ 与各均值向量 $\mathbf{\mu_i}$ $(1 \le i \le k)$的距离：
             $d_{ji} = \Vert \mathbf{x_j} - \mathbf{\mu_i} \Vert^2_2$ ；  
&emsp;&emsp; 根据距离最近的均值向量确定 $\mathbf{x_j}$ 的簇标记：
             $\lambda_j = argmin_{i\in \{ 1, 2, \dots, k \}}d_{ji} $  
&emsp;&emsp; 将样本 $\mathbf{x_j}$ 划入相应的簇：
             $ C_{\lambda_j} =  C_{\lambda_j} \cup \{ \mathbf{x_j} \} $  
&emsp; **end for**  
&emsp; **for** $i = 1, 2, \dots, k$ **do**  
&emsp;&emsp; 计算新均值向量： $ \mu^{'}_i = \frac{1}{\vert C_i \vert}\sum_{\mathbf{x}\in C_i}\mathbf{x} $  
&emsp;&emsp; **if** $\mathbf{\mu_i^{'} \neq \mathbf{\mu_i}}$ **then**  
&emsp;&emsp;&emsp; 将当前的均值向量 $\mathbf{\mu_i}$ 更新为 $\mathbf{\mu_i^{'}}$  
&emsp;&emsp; **else**  
&emsp;&emsp;&emsp; 保持当前均值向量不变  
&emsp;&emsp; **end if**  
&emsp; **end for**  
**util** 当前均值向量均未更新  
**输出**：簇划分 $ C = \{ C_1, C_2, \dots, C_k\} $

In [11]:
def kMeans(dataSet, k, distMeas=distEclud, createCent=randCent):
    m = shape(dataSet)[0]
    # 保存每个样本所属的簇及到中心点的距离
    clusterAssment = mat(zeros((m, 2)))
    # 各均值向量
    centroids = createCent(dataSet, k)
    clusterChanged = True
    while clusterChanged:
        clusterChanged = False
        for i in xrange(m):
            minDist = inf; minIndex = -1
            for j in xrange(k):
                distJI = distMeas(centroids[j,:], dataSet[i,:])
                if distJI < minDist:
                    minDist = distJI; minIndex = j
            if clusterAssment[i, 0] != minIndex:
                # 若有改变，则继续循环
                clusterChanged = True
            clusterAssment[i,:] = minIndex, minDist**2
        print(centroids)
        for cent in xrange(k):
            # 计算新的均值向量
            ptsInClust = dataSet[nonzero(clusterAssment[:,0].A == cent)[0]]
            centroids[cent, :] = mean(ptsInClust, axis=0)
    return centroids, clusterAssment

In [13]:
myCentroids, clustAssing = kMeans(datMat, 4)
#print(myCentroids, clustAssing)

[[-0.42895319  2.42895702]
 [-4.92526135 -2.87653537]
 [-3.19766893  4.45393477]
 [ 1.34722789 -0.39182675]]
[[ 0.78702448  3.24838505]
 [-3.53973889 -2.89384326]
 [-3.00520133  2.93274117]
 [ 2.803603   -1.57435221]]
[[ 2.225975    3.17026943]
 [-3.38237045 -2.9473363 ]
 [-2.64677572  2.78993217]
 [ 2.8692781  -2.54779119]]
[[ 2.6265299   3.10868015]
 [-3.38237045 -2.9473363 ]
 [-2.46154315  2.78737555]
 [ 2.80293085 -2.7315146 ]]
